name: Unit Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    name: Run Linting and Tests

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          version: 14.x

      - name: build
        env:
          TURBO_TOKEN: ${{ secrets.TURBO_REPO_API_KEY }}
          TURBO_TEAM: skill-recordings
          TURBO_PROJECT: turbo-playground
        run: yarn run build:ci
